words = [
	"listchanges",
	"umask",
	"fs.protected_fifos",
	"rkhunter",
	"syslog",
	"auditd",
	"libpam",
	"fail2ban",
	"listbugs",
	"fifos",
	"fs",
	"sysRq",
	"debsums",
	"passwdqc",
	"libpam",
	"tmpdir",
	"fs",
	"UEFI",
	"avahi",
	"Lynis",
	"passwdqc",
	"kptr",
	"bpf",
	"rp",
	"avahi",
	"dccp",
	"tipc",
	"BTS",
	"jit",
	"dumpable",
]
