- name: Create aur_builder user
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
  become: true

- name: Allow aur_builder to use pacman without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
  become: true

- name: Install Official packages
  community.general.pacman:
    name: "{{ desktop_native_packages }}"
    state: present
  when: ansible_os_family == "Archlinux"

- name: Install Official packages
  community.general.pacman:
    name: "{{ desktop_native_host_packages }}"
    state: present
  when: system_role == "daily_driver"

- name: Check if yay is installed
  ansible.builtin.command: which yay
  register: desktop_yay_check
  ignore_errors: true
  changed_when: false

- name: Clone the github repo yay
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay-bin.git'
    dest: /tmp/yay-bin
    version: master
  become: true
  become_user: aur_builder
  when: desktop_yay_check.rc != 0

- name: Compile yay via makepkg
  ansible.builtin.command:
    cmd: makepkg -si --noconfirm
    chdir: /tmp/yay-bin
    creates: /usr/bin/yay
  become: true
  become_user: aur_builder
  when: desktop_yay_check.rc != 0

- name: Install AUR packages with yay
  kewlfft.aur.aur:
    name: "{{ desktop_aur_packages }}"
    use: yay
    state: present
  become: true
  become_user: aur_builder

- name: Install AUR packages daily_driver
  when: system_role == 'daily_driver'
  kewlfft.aur.aur:
    name: "{{ desktop_aur_host_packages }}"
    state: present
  become: true
  become_user: aur_builder
