hardening_required_packages:
  - fail2ban
  - arch-audit
  - rkhunter

hardening_modules_to_disable:
  - name: hfs
    reason: unused filesystem, reduces attack surface
  - name: hfsplus
    reason: unused filesystem, reduces attack surface
  - name: firewire-core
    reason: block physical DMA attack vector
