- name: Copy AIDE package
  ansible.builtin.copy:
    src: aide-0.19.3.pkg.tar.zst
    dest: /tmp/aide-0.19.3.tar.gz.zst
    mode: '0600'
    owner: root
    group: root

- name: Install AIDE from local package
  community.general.pacman:
    name: /tmp/aide-0.19.3.tar.gz.zst
    state: present

- name: Create AIDE directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - /var/lib/aide
    - /var/log/aide

- name: Deploy AIDE config
  ansible.builtin.template:
    src: aide.conf.j2
    dest: /etc/aide.conf
    owner: root
    group: root
    mode: '0600'

- name: Initialize AIDE database
  ansible.builtin.command: aide --init
  args:
    creates: /var/lib/aide/aide.db.new.gz

- name: Activated AIDE database
  ansible.builtin.command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    creates: /var/lib/aide/aide.db.gz

- name: Deploy aidecheck service
  ansible.builtin.copy:
    src: aidecheck.service
    dest: /etc/systemd/system/aidecheck.service
    owner: root
    group: root
    mode: '0644'

- name: Aidecheck.timer
  ansible.builtin.copy:
    src: aidecheck.timer
    dest: /etc/systemd/system/aidecheck.timer
    owner: root
    group: root
    mode: '0644'

- name: Enable and start the timer and service
  ansible.builtin.systemd:
    name: aidecheck.timer
    enabled: true
    state: started
    daemon_reload: true
