- name: Dissable unused network protocols
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disable-protocols.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      install dccp /bin/false
      install sctp /bin/false
      install rds /bin/false
      install tipc /bin/false

- name: Disable unused kernel modules
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/disable-{{ item.name }}.conf"
    content: |
      # Ansible managed: {{ item.reason }}
      install {{ item.name }} /bin/false
    owner: root
    group: root
    mode: '0644'
  loop: "{{ hardening_modules_to_disable }}"

- name: Unload modules if actives in memory
  ansible.builtin.command: "modprobe -r {{ item.name }}"
  loop: "{{ hardening_modules_to_disable }}"
  failed_when: false
  changed_when: false
