- name: Install necessary packages
  ansible.builtin.import_tasks: prerequisites.yaml

- name: Configure ssh hardening
  ansible.builtin.import_tasks: ssh.yaml

- name: Hardening passwords
  ansible.builtin.import_tasks: passwords.yaml

- name: Php configure
  ansible.builtin.import_tasks: php.yaml

- name: Set up AIDE
  ansible.builtin.import_tasks: aide.yaml

- name: Hardening kernel
  ansible.builtin.import_tasks: kernel.yaml

- name: Adding rules for auditd
  ansible.builtin.import_tasks: auditd.yaml
