- name: Hardening passwords
  hosts: all
  become: yes

  tasks:
    - name: Hardening /etc/login.defs
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        regexp: '^(#\s*)?{{ item.key }}\b'
        line: "{{item.key}} {{item.value}}"
        state: present
        backup: yes
      loop:
        - { key: 'UMASK', value: '027' }
        - { key: 'PASS_MIN_DAYS', value: '3' }
        - { key: 'PASS_MAX_DAYS', value: '99999' }
        - { key: 'SHA_CRYPT_MIN_ROUNDS', value: '100000' }

    - name: Hardening /etc/security/pwquality.conf
      ansible.builtin.lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^(#\s*)?{{ item.key }}\b'
        line: "{{item.key}} = {{item.value}}"
        state: present
        backup: yes
      loop:
        - { key: 'minlen', value: '15' }
        - { key: 'dcredit', value: '-1' }
        - { key: 'ucredit', value: '-1' }
        - { key: 'lcredit', value: '-1' }
        - { key: 'ocredit', value: '-1' }
        - { key: 'minclass', value: '4' }

    - name: Ensure pam-quality is active in /etc/pam.d/passwd
      ansible.builtin.lineinfile:
        path: /etc/pam.d/passwd
        regexp: '^passwd.*pam_quality\.so'
        line: 'password requisite pam_quality.so retry=3'
        insertbefore: 'password\s+include\s+system-auth'
        state: present
        backup: yes

    - name: Enforce password quality for root
      ansible.builtin.lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^#\s*enforce_for_root'
        line: 'enforce_for_root'
        state: present
        backup: yes
