- name: Php censor info
  ansible.builtin.lineinfile:
    path: /etc/php/php.ini
    regexp: '^(;\s*)?{{ item.key }}\b'
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backup: true

  loop:
    - { key: 'expose_php', value: 'off' }
    - { key: 'allow_url_fopen', value: 'off' }
