- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true
  when: ansible_os_family == "Archlinux"

- name: Intall required programs
  community.general.pacman:
    name: "{{ hardening_required_packages }}"
    state: present
  become: true
  when: ansible_os_family == "Archlinux"
