required_packages:
  - man-db
  - man-pages
  - base
  - base-devel
  - git
  - wget
  - btop
  - ttf-jetbrains-mono-nerd
  - python
  - python-pipx
  - nautilus
  - neovim
  - ghostty
  - tmux
  - jq
  - zoxide
  - pacman-contrib
  - rofi
  - atuin
  - yazi
  - zsh
  - zsh-completions
  - fzf
  - bat
  - fastfetch
  - fd
  - stow
