- name: Clone the config repo i3
  ansible.builtin.git:
    repo: 'https://github.com/it2000-the-original/i3wm-Dotfiles'
    dest: "{{ ansible_env.HOME }}/i3"
    version: main
    update: true
  become_user: "{{ ansible_user_id }}"
  become: true
  when: ansible_os_family == "Archlinux"

- name: Give execution permision to the script
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/i3/install.sh"
    mode: '0755'
    state: file
  become: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"

- name: Run the install script for the i3 repo and create a mark
  ansible.builtin.shell: ./install.sh && touch exists_already.txt
  args:
    chdir: "{{ ansible_env.HOME }}/i3"
    creates: "{{ ansible_env.HOME }}/i3/exists_already.txt"
  become_user: "{{ ansible_user_id }}"
  become: true
  changed_when: true
