- name: Download the dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/AFHH999/Dotfiles'
    dest: "/home/{{ ansible_env.HOME }}/Dotfiles"
    version: main
    update: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"

- name: stow the config dotfiles
  ansible.builtin.shell: stow */
  args:
    chdir: "{{ ansible_env.HOME }}/Dotfiles"
  become: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"
