- name: Download the dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/AFHH999/Dotfiles'
    dest: " {{ ansible_env.HOME }}/Dotfiles "
    version: main
    update: true
    force: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"

- name: Make sure the dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Dotfiles"
    state: directory
    mode: '0755'
  when: ansible_os_family == "Archlinux"

- name: stow the config dotfiles
  ansible.builtin.shell: stow */
  args:
    chdir: "{{ ansible_env.HOME }}/Dotfiles"
  become: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"
