- name: Download the dotfiles repo
  ansible.builtin.git:
    repo: 'https://github.com/AFHH999/Dotfiles'
    dest: "{{ ansible_env.HOME }}/Dotfiles"
    version: main
    update: true
    force: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"

- name: Make sure the dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Dotfiles"
    state: directory
    mode: '0755'
  when: ansible_os_family == "Archlinux"

- name: stow the config dotfiles
  ansible.builtin.shell: |
    set -e
    for pkg in */; do
        if [ -d "$pkg" ] && [ "$pkg" != ".git/" ]; then 
        stow -v -t "{{ ansible_env.HOME }}/.config" "${pkg%/}"
      fi
    done
  args:
    chdir: "{{ ansible_env.HOME }}/Dotfiles"
    executable: /bin/bash
  become: true
  become_user: "{{ ansible_user_id }}"
  when: ansible_os_family == "Archlinux"
