- name: Update pacman cache if stale
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family == "Archlinux"

- name: Install Official packages in Arch
  community.general.pacman:
    name: "{{ required_packages }}"
    state: present
  when: ansible_os_family == "Archlinux"

- name: check if pynvim is installed
  ansible.builtin.command: pipx list
  register: pipx_list
  change_when: false
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

- name: Install pynvim
  ansible.builtin.command: pipx install pynvim
  when: "'pynvim' not in pipx_list.stdout"
  become: true
  become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
