required_packages:
  - gdb
  - gef
  - ghidra
  - radare2
  - binwalk
  - python-pwntools
  - strace
  - ltrace
  - valgrind
  - python-pip
  - checksec
  - nasm
  - yasm
  - wireshark-qt
  - tcpdump
  - lldb
  - python-pycryptodomex
  - python-requests
  - upx
  - binutils

