desktop_env_required_packages:
  - i3-wm
  - i3status
  - i3lock

desktop_env_aur_packages:
  - dunst
  - rofi
  - feh
  - mpv
  - picom
  - nemo
  - cinnamon-translations
  - network-manager-applet
  - xss-lock
  - ttf-fira-code
  - nerd-fonts-fira-code
  - brightnessctl
  - alsa-utils
  - polkit
  - polkit-gnome
  - python-pynvim
  - blueman
  - acpi
